# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, font

# Util imports
import constant

# Button text
buttonText1 = "button1"
buttonText2 = "button2"
buttonText3 = "button3"
buttonText4 = "button4"
buttonText5 = "button5"

# Path
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.geometry("1512x982")
window.configure(bg = "#FFFFFF")

# Constants
BUTTON_FONT = font.Font(family="inter", size=18)
NAME_FONT = font.Font(family="inter", size=18)
TITLE_FONT = font.Font(family="inter", size=18)

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    416.6158142089844,
    2.2737367544323206e-13,
    423.8770751953125,
    981.9731445312502,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    text=buttonText1,
    image=button_image_1,
    compound="center",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=60,
    y=200,
    width=295.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    text=buttonText2,
    image=button_image_2,
    compound="center",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=60,
    y=300,
    width=295.0,
    height=70.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    text=buttonText3,
    image=button_image_3,
    compound="center",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=60,
    y=400,
    width=295.0,
    height=70.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    text=buttonText4,
    image=button_image_4,
    compound="center",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=60,
    y=505,
    width=295.0,
    height=70.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    text=buttonText5,
    image=button_image_5,
    compound="center",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=60,
    y=605,
    width=295.0,
    height=70.0
)

# Button fonts
button_1['font'] = BUTTON_FONT
button_2['font'] = BUTTON_FONT
button_3['font'] = BUTTON_FONT
button_4['font'] = BUTTON_FONT
button_5['font'] = BUTTON_FONT

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    256.0,
    133.00000000000023,
    image=entry_image_1
)
"""
entry_1 = Text(
    bd=0,
    bg="#EEEEEE",
    highlightthickness=0
)
entry_1.place(
    x=156.0,
    y=103.00000000000023,
    width=200.0,
    height=58.0
)
"""
"""
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1025.0,
    120.00000000000023,
    image=entry_image_2
)
"""
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.pack()
entry_2.insert("1.0", "Xiao Zhang")
entry_2.configure(font=("inter", 36, "bold"))
entry_2.configure(state="disabled")
entry_2.place(
    x=825,
    y=90,
    width=400,
    height=60
)


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    96.84042358398438,
    127.00000000000023,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    646.574462890625,
    202.00000000000023,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    849.800537109375,
    267.0000000000002,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    849.800537109375,
    195.00000000000023,
    image=image_image_4
)

canvas.create_rectangle(
    534.574462890625,
    390.0000000000002,
    1384.574462890625,
    890.0000000000002,
    fill="#F0F0F0",
    outline="")

# Health Bar
#   Background
canvas.create_rectangle(
    890,
    170,
    1240,
    220,
    fill=constant.GRAY,
    outline="")
#   Health
canvas.create_rectangle(
    895,
    175,
    1235,
    215,
    fill=constant.RED,
    outline="")

# XP Bar
#   Background
canvas.create_rectangle(
    890,
    240,
    1240,
    290,
    fill=constant.GRAY,
    outline="")
#   XP
canvas.create_rectangle(
    895,
    245,
    1235,
    285,
    fill=constant.YELLOW,
    outline="")

window.resizable(False, False)
window.mainloop()
